---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  "/events":
    post:
      summary: Create a new Event
      tags:
      - Events
      parameters: []
      responses:
        '201':
          description: event created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                event:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    start_date:
                      type: datetime
                    start_time:
                      type: datetime
                    end_time:
                      type: datetime
                    recurrence:
                      type: boolean
                    recurrence_week:
                      type: integer
                    ends_on:
                      type: time
                    repeat_days:
                      type: array
                      items:
                        days:
                          type: string
                  required:
                  - name
                  - description
                  - start_time
                  - end_time
                  - start_date
                  - recurrence
              required:
              - event
  "/events/{id}/assign_employees":
    post:
      summary: Assign employees to events
      tags:
      - Events
      parameters:
      - name: id
        in: path
        description: event_id where employee will be assigned
        required: true
        schema:
          type: string
      responses:
        '201':
          description: employees assigned
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                employee_emails:
                  type: array
                  items:
                    days:
                      type: string
  "/events/{id}/update_recurrences":
    post:
      summary: update recurring event
      tags:
      - Events
      parameters:
      - name: id
        in: path
        description: event_id which will be updated
        required: true
        schema:
          type: string
      responses:
        '201':
          description: event updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                update_type:
                  type: string
                event:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    start_date:
                      type: datetime
                    start_time:
                      type: datetime
                    end_time:
                      type: datetime
                    recurrence:
                      type: boolean
                    recurrence_week:
                      type: integer
                    ends_on:
                      type: time
                    repeat_days:
                      type: array
                      items:
                        days:
                          type: string
              required:
              - event
  "/login":
    post:
      summary: create session
      tags:
      - Session
      parameters: []
      responses:
        '201':
          description: Session created
        '401':
          description: Unauthorised
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/register":
    post:
      summary: Create a new Owner and company
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: owner created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                company_name:
                  type: string
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - password
                  - password_confirmation
              required:
              - company_name
              - user
  "/employees":
    post:
      summary: add employee to company
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: Session created
        '422':
          description: Unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - password
                  - password_confirmation
              required:
              - user
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
